GET http://localhost:5164/games


###
GET http://localhost:5164/games/2

###

POST http://localhost:5164/games
Content-Type: application/json

{
  "Name": "Minecraft",
  "Genre": "Sandbox",
  "Price": 26.95,
  "ReleaseDate": "2011-11-18"
}

###

PUT http://localhost:5164/games/3
Content-Type: application/json

{
  "Name": "Minecraft Turbo",
  "Genre": "Sandbox",
  "Price": 20.95,
  "ReleaseDate": "2011-11-20"
}
